apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-quickstart-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-quickstart
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-quickstart
    spec:
      containers:
        - name: spring-boot-quickstart
          image: localhost:5000/spring-boot-quickstart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080